/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthylife;

import Michael.WellnessEducation;
import Tien.HabitBuilder;
import Alex.HealthTracker;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author mikey
 */
public class HealthGUI extends javax.swing.JFrame {
    
    private ArrayList<User> users = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HealthGUI.class.getName());

    /**
     * Creates new form HealthGUI
     */
    public HealthGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        healthProfileLBL = new javax.swing.JLabel();
        ageLBL = new javax.swing.JLabel();
        heightLBL = new javax.swing.JLabel();
        weightLBL = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        heightTF = new javax.swing.JTextField();
        weightTF = new javax.swing.JTextField();
        manRB = new javax.swing.JRadioButton();
        womanRB = new javax.swing.JRadioButton();
        healthTrackerBTN = new javax.swing.JButton();
        habitBuilderBTN = new javax.swing.JButton();
        WellnessEducationBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        desk1LBL = new javax.swing.JLabel();
        pictureLBL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name2TF = new javax.swing.JTextField();
        password2TF = new javax.swing.JTextField();
        desc3LBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        checkBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        desc2LBL = new javax.swing.JLabel();
        passwordTF = new javax.swing.JTextField();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        passwordLBL = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(627, 498));
        setResizable(false);

        healthProfileLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        healthProfileLBL.setText("Health Profile");

        ageLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ageLBL.setText("Age");

        heightLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        heightLBL.setText("Height");

        weightLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        weightLBL.setText("Weight");

        weightTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTFActionPerformed(evt);
            }
        });

        manRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manRB.setText("Man");

        womanRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        womanRB.setText("Woman");

        healthTrackerBTN.setBackground(new java.awt.Color(120, 140, 180));
        healthTrackerBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        healthTrackerBTN.setForeground(new java.awt.Color(255, 255, 255));
        healthTrackerBTN.setText("Health Tracker");
        healthTrackerBTN.setBorderPainted(false);
        healthTrackerBTN.setOpaque(true);
        healthTrackerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthTrackerBTNActionPerformed(evt);
            }
        });

        habitBuilderBTN.setBackground(new java.awt.Color(120, 140, 180));
        habitBuilderBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        habitBuilderBTN.setForeground(new java.awt.Color(255, 255, 255));
        habitBuilderBTN.setText("Habit Builder");
        habitBuilderBTN.setBorderPainted(false);
        habitBuilderBTN.setOpaque(true);
        habitBuilderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitBuilderBTNActionPerformed(evt);
            }
        });

        WellnessEducationBTN.setBackground(new java.awt.Color(120, 140, 180));
        WellnessEducationBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WellnessEducationBTN.setForeground(new java.awt.Color(255, 255, 255));
        WellnessEducationBTN.setText("Wellness Education");
        WellnessEducationBTN.setBorderPainted(false);
        WellnessEducationBTN.setOpaque(true);
        WellnessEducationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WellnessEducationBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(120, 140, 180));
        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(255, 0, 0));
        exitBTN.setText("EXIT");
        exitBTN.setBorderPainted(false);
        exitBTN.setOpaque(true);
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        saveBTN.setBackground(new java.awt.Color(120, 140, 180));
        saveBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(255, 255, 255));
        saveBTN.setText("SAVE");
        saveBTN.setBorderPainted(false);
        saveBTN.setOpaque(true);
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        clearBTN.setBackground(new java.awt.Color(120, 140, 180));
        clearBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBTN.setForeground(new java.awt.Color(255, 255, 255));
        clearBTN.setText("CLEAR");
        clearBTN.setBorderPainted(false);
        clearBTN.setOpaque(true);
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        desk1LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        desk1LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desk1LBL.setText("<html>Your personal health hub – check your BMI,<br> build better habits &amp; explore wellness tips.</html> ");

        pictureLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthylife/health-medical-healthcare-health.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        password2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2TFActionPerformed(evt);
            }
        });

        desc3LBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        desc3LBL.setText("Sign In");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name");

        checkBTN.setBackground(new java.awt.Color(120, 140, 180));
        checkBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkBTN.setForeground(new java.awt.Color(255, 255, 255));
        checkBTN.setText("SIGN IN");
        checkBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(desc3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(checkBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desc3LBL)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(name2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(password2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        desc2LBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        desc2LBL.setText("Don't have an account ?, Feel free to Register");

        nameLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameLBL.setText("Name");

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        passwordLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordLBL.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(pictureLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(healthProfileLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(desk1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(healthTrackerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(habitBuilderBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(WellnessEducationBTN)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(weightLBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(heightLBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(heightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(nameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(womanRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(desc2LBL)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearBTN)
                        .addGap(18, 18, 18)
                        .addComponent(exitBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {WellnessEducationBTN, habitBuilderBTN, healthTrackerBTN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthProfileLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pictureLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desk1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthTrackerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habitBuilderBTN)
                    .addComponent(WellnessEducationBTN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(desc2LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(passwordLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightLBL)
                            .addComponent(heightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLBL))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(weightLBL)
                                    .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manRB)
                            .addComponent(womanRB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBTN)
                            .addComponent(clearBTN)
                            .addComponent(exitBTN))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {WellnessEducationBTN, habitBuilderBTN, healthTrackerBTN});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTFActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void healthTrackerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthTrackerBTNActionPerformed
        // TODO add your handling code here:
        new HealthTracker().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_healthTrackerBTNActionPerformed

    private void habitBuilderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitBuilderBTNActionPerformed
        // TODO add your handling code here:
        new HabitBuilder().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_habitBuilderBTNActionPerformed

    private void WellnessEducationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WellnessEducationBTNActionPerformed
        // TODO add your handling code here:
        new WellnessEducation().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_WellnessEducationBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        try{
            String name = nameTF.getText();
            String age = ageTF.getText();
            String password = passwordTF.getText();
            String height = heightTF.getText();
            String weight = weightTF.getText();
            String gender = "";
            
            if(manRB.isSelected()){
                gender = "Man";
            }else if(womanRB.isSelected()){
                gender = "Woman";
            }else{
                gender = "Neutral";
            }
            
            for (User u : users) {
                if (u.getName().equals(name)) {
                    JOptionPane.showMessageDialog(null, "That username already exists. Choose another name.");
                    return;
                }
            }
            
            if (name.equals("") || age.equals("") || height.equals("") || weight.equals("")){
                JOptionPane.showMessageDialog(null,
                    "Please fill in all fields and select gender.");
            return;
        }
            int ageValue = Integer.parseInt(age);
            double heightValue = Double.parseDouble(height);
            double weightValue = Double.parseDouble(weight);

            User newUser = new User(name, password, ageValue, heightValue, weightValue, gender);
            users.add(newUser);

        String msg = "You entered:\n\n"
                   + "Name: " + name + "\n"
                   + "Age: " + age + " years old\n"
                   + "Height: " + height + " cm\n"
                   + "Weight: " + weight + " kg\n"
                   + "Gender: " + gender;

        JOptionPane.showMessageDialog(null, msg);            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " +e);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
                try{
            nameTF.setText("");
            name2TF.setText("");
            passwordTF.setText("");
            password2TF.setText("");
            ageTF.setText("");
            heightTF.setText("");
            weightTF.setText("");
            manRB.setSelected(false);
            womanRB.setSelected(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:" +e);
        }                                       
    }//GEN-LAST:event_clearBTNActionPerformed

    private void password2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2TFActionPerformed

    private void checkBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBTNActionPerformed
        // TODO add your handling code here:
    String name = name2TF.getText();
    String pass = password2TF.getText(); // if JPasswordField: new String(signPasswordPF.getPassword())

    if (name.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter name and password.");
        return;
    }

    for (User u : users) {
        if (u.getName().equalsIgnoreCase(name)) {
            if (u.getPassword().equals(pass)) {
                JOptionPane.showMessageDialog(null, "Welcome, " + u.getName() + "!\n" + u.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect password.");
            }
            return; // stop after finding the user
        }
    }

    JOptionPane.showMessageDialog(null, "User not found.");

    }//GEN-LAST:event_checkBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HealthGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton WellnessEducationBTN;
    private javax.swing.JLabel ageLBL;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton checkBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JLabel desc2LBL;
    private javax.swing.JLabel desc3LBL;
    private javax.swing.JLabel desk1LBL;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton habitBuilderBTN;
    private javax.swing.JLabel healthProfileLBL;
    private javax.swing.JButton healthTrackerBTN;
    private javax.swing.JLabel heightLBL;
    private javax.swing.JTextField heightTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton manRB;
    private javax.swing.JTextField name2TF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField password2TF;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JLabel pictureLBL;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel weightLBL;
    private javax.swing.JTextField weightTF;
    private javax.swing.JRadioButton womanRB;
    // End of variables declaration//GEN-END:variables
}
