/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tien;

/**
 *
 * @author Tien
 */

import Alex.HealthTracker;
import Michael.WellnessEducation;
import healthylife.HealthGUI;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class HabitBuilder extends javax.swing.JFrame {
    String[] nameArray = new String[100];
    String[] descriptionArray = new String[100];
    boolean[] completedArray = new boolean[100];
    boolean[] notCompletedArray = new boolean[100];
    
    int count = 0;
    int completedCount = 0;
    int notCompletedCount = 0;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HabitBuilder.class.getName());

    /**
     * Creates new form HabitBuilder
     */
    public HabitBuilder() {
    //    descLBL.setText("Hello, here it's my habit bulder, you can add your name,\n strak, descriptopm, and tick completed or not");
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        habitBuilderLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        descriptionLBL = new javax.swing.JLabel();
        dateLBL = new javax.swing.JLabel();
        check2LBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        descriptionTF = new javax.swing.JTextField();
        streakTF = new javax.swing.JTextField();
        check2CB = new javax.swing.JCheckBox();
        saveBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        viewBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        healthTrackerBTN = new javax.swing.JButton();
        WellnessEducationBTN = new javax.swing.JButton();
        mainMenuBTN = new javax.swing.JButton();
        checkLBL1 = new javax.swing.JLabel();
        check1CB = new javax.swing.JCheckBox();
        descLBL = new javax.swing.JLabel();
        habitTipsBTN = new javax.swing.JButton();
        tutorialBTN = new javax.swing.JButton();
        pictureLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        habitBuilderLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        habitBuilderLBL.setForeground(new java.awt.Color(30, 40, 60));
        habitBuilderLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        habitBuilderLBL.setText("Habit Builder");

        nameLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameLBL.setText("Name");

        descriptionLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        descriptionLBL.setText("Description");

        dateLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLBL.setText("Streak");

        check2LBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        check2LBL.setText("Not Completed");

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        streakTF.setEditable(false);

        check2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2CBActionPerformed(evt);
            }
        });

        saveBTN.setBackground(new java.awt.Color(120, 140, 180));
        saveBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(255, 255, 255));
        saveBTN.setText("SAVE");
        saveBTN.setBorderPainted(false);
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        clearBTN.setBackground(new java.awt.Color(120, 140, 180));
        clearBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearBTN.setForeground(new java.awt.Color(255, 255, 255));
        clearBTN.setText("CLEAR");
        clearBTN.setBorderPainted(false);
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        viewBTN.setBackground(new java.awt.Color(120, 140, 180));
        viewBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewBTN.setText("VIEW");
        viewBTN.setBorderPainted(false);
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(120, 140, 180));
        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(220, 40, 60));
        exitBTN.setText("EXIT");
        exitBTN.setBorderPainted(false);
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        healthTrackerBTN.setBackground(new java.awt.Color(120, 140, 180));
        healthTrackerBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        healthTrackerBTN.setForeground(new java.awt.Color(255, 255, 255));
        healthTrackerBTN.setText("Health Tracker");
        healthTrackerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthTrackerBTNActionPerformed(evt);
            }
        });

        WellnessEducationBTN.setBackground(new java.awt.Color(120, 140, 180));
        WellnessEducationBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WellnessEducationBTN.setForeground(new java.awt.Color(255, 255, 255));
        WellnessEducationBTN.setText("Wellness Education");
        WellnessEducationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WellnessEducationBTNActionPerformed(evt);
            }
        });

        mainMenuBTN.setBackground(new java.awt.Color(120, 140, 180));
        mainMenuBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainMenuBTN.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBTN.setText("Main Menu");
        mainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBTNActionPerformed(evt);
            }
        });

        checkLBL1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkLBL1.setText("Completed ");

        check1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1CBActionPerformed(evt);
            }
        });

        habitTipsBTN.setBackground(new java.awt.Color(120, 140, 180));
        habitTipsBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        habitTipsBTN.setForeground(new java.awt.Color(255, 255, 255));
        habitTipsBTN.setText("Habit Tips");
        habitTipsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitTipsBTNActionPerformed(evt);
            }
        });

        tutorialBTN.setBackground(new java.awt.Color(120, 140, 180));
        tutorialBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tutorialBTN.setForeground(new java.awt.Color(255, 255, 255));
        tutorialBTN.setText("Tutorial");
        tutorialBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialBTNActionPerformed(evt);
            }
        });

        pictureLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tien/protection.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(pictureLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habitBuilderLBL)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(habitTipsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(saveBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(clearBTN, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(30, 30, 30)
                                                    .addComponent(exitBTN))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(viewBTN)))))
                                    .addComponent(tutorialBTN, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descriptionLBL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(nameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dateLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(streakTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(checkLBL1)
                                        .addGap(40, 40, 40)
                                        .addComponent(check1CB))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(check2LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(check2CB))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(healthTrackerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(WellnessEducationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mainMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clearBTN, exitBTN, saveBTN, viewBTN});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {WellnessEducationBTN, habitTipsBTN, healthTrackerBTN, mainMenuBTN, tutorialBTN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(habitBuilderLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pictureLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(healthTrackerBTN)
                                    .addComponent(WellnessEducationBTN)
                                    .addComponent(mainMenuBTN))))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLBL)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLBL)
                            .addComponent(streakTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(check1CB)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkLBL1)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(descriptionLBL)
                        .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(check2LBL)
                        .addComponent(check2CB)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tutorialBTN)
                        .addGap(18, 18, 18)
                        .addComponent(habitTipsBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBTN)
                            .addComponent(viewBTN))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearBTN)
                            .addComponent(exitBTN))
                        .addGap(27, 27, 27))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clearBTN, exitBTN, saveBTN, viewBTN});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {WellnessEducationBTN, healthTrackerBTN, mainMenuBTN, tutorialBTN});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check2CBActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void healthTrackerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthTrackerBTNActionPerformed
        // TODO add your handling code here:
         new HealthTracker().setVisible(true);
         this.setVisible(false);
         System.out.println("closed");
         this.dispose();
    }//GEN-LAST:event_healthTrackerBTNActionPerformed

    private void WellnessEducationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WellnessEducationBTNActionPerformed
        // TODO add your handling code here:
        new WellnessEducation().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
       

    }//GEN-LAST:event_WellnessEducationBTNActionPerformed

    private void mainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBTNActionPerformed
        // TODO add your handling code here:
        new HealthGUI().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_mainMenuBTNActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        try {
            String name = nameTF.getText();
            String description = descriptionTF.getText();
            boolean completedToday = check1CB.isSelected();
            boolean notCompletedToday = check2CB.isSelected();
            
            // check all three "boxes"
            if (name.isEmpty() || description.isEmpty()) {
                JOptionPane.showMessageDialog(null,"Please fill in both Name and Description.");
                return;
            }

            if (!completedToday && !notCompletedToday)  {
                JOptionPane.showMessageDialog(null,"Please tick the box.");
                return;
               
            }
            
            nameArray[count] = name;
            descriptionArray[count] = description;
            completedArray[count] = completedToday;
            notCompletedArray[count] = notCompletedToday;
            count++;
            
            if(completedToday){
                completedCount++;
            }else if(notCompletedToday){
                notCompletedCount ++;
            }

            streakTF.setText(String.valueOf(count));

            JOptionPane.showMessageDialog(null, "Habit saved!");

            nameTF.setText("");
            descriptionTF.setText("");
            check1CB.setSelected(false);
            check2CB.setSelected(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " +e);
        }    
    }//GEN-LAST:event_saveBTNActionPerformed

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTNActionPerformed
        // TODO add your handling code here:
        try {
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "No habits saved yet.");
                return;
            }

            String msg = "Total Habits Streak: " + count + "\n" +
                         "Total Completed : " + completedCount + "\n" +
                         "Total Not Completed : " + notCompletedCount + "\n\n";

            for (int i = 0; i < count; i++) {
                msg += "Habit #" + (i + 1) + "\n";
                msg += "Name: " + nameArray[i] + "\n";
                msg += "Description: " + descriptionArray[i] + "\n";
                if(completedArray[i]){
                     msg += "Completed: Yes\n";
                }else if(notCompletedArray[i]){
                        msg += "Completed: No\n";;                   
                }
            }

            displayTA.setText(msg);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }   
    }//GEN-LAST:event_viewBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        try {
            for (int i = 0; i < count; i++) {
                nameArray[i] = null;
                descriptionArray[i] = null;
                completedArray[i] = false;
                notCompletedArray[i] = false;
            }
            count = 0;
            
            displayTA.setText("");
            streakTF.setText("");        

            JOptionPane.showMessageDialog(null, "All habits cleared.");

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_clearBTNActionPerformed

    private void check1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check1CBActionPerformed

    private void habitTipsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitTipsBTNActionPerformed
        // TODO add your handling code here:
        HabitTips tips = new HabitTips();
        ArrayList<String> list = tips.getAllTips();
        
        String message = "";
        for(String t :list){
            message += "- " + t + "\n";
        }
        displayTA.setText(message);
    }//GEN-LAST:event_habitTipsBTNActionPerformed

    private void tutorialBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialBTNActionPerformed
        // TODO add your handling code here:
        HabitGuide guide = new HabitGuide();
        
        displayTA.setText(guide.getTutorial());
    }//GEN-LAST:event_tutorialBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HabitBuilder().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton WellnessEducationBTN;
    private javax.swing.JCheckBox check1CB;
    private javax.swing.JCheckBox check2CB;
    private javax.swing.JLabel check2LBL;
    private javax.swing.JLabel checkLBL1;
    private javax.swing.JButton clearBTN;
    private javax.swing.JLabel dateLBL;
    private javax.swing.JLabel descLBL;
    private javax.swing.JLabel descriptionLBL;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel habitBuilderLBL;
    private javax.swing.JButton habitTipsBTN;
    private javax.swing.JButton healthTrackerBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel pictureLBL;
    private javax.swing.JButton saveBTN;
    private javax.swing.JTextField streakTF;
    private javax.swing.JButton tutorialBTN;
    private javax.swing.JButton viewBTN;
    // End of variables declaration//GEN-END:variables
}
