/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Michael;

import java.util.ArrayList;
import java.util.Random;
import Alex.HealthTracker;
import Tien.HabitBuilder;
import healthylife.HealthGUI;
/**
 *
 * @author mikey
 */
public class WellnessEducation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WellnessEducation.class.getName());
    private ArrayList<HealthTip> tipsList = new ArrayList<>();
    private ArrayList<QuizQuestion> quizList = new ArrayList<>();
    private int currentQuizIndex = 0;
    private int score = 0;
    private boolean quizStarted = false;


    /**
     * Creates new form WellnessEducation
     */
    public WellnessEducation() {
        initComponents();
        loadTips();
        loadQuestions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tipsTA = new javax.swing.JTextArea();
        WellnessEducationLBL = new javax.swing.JLabel();
        mainMenuBTN = new javax.swing.JButton();
        HabitBuilderBTN = new javax.swing.JButton();
        HealthTrackerBTN = new javax.swing.JButton();
        EXITbtn = new javax.swing.JButton();
        healthtipsLBL = new javax.swing.JLabel();
        showtipBTN = new javax.swing.JButton();
        optionaRB = new javax.swing.JRadioButton();
        optionbRB = new javax.swing.JRadioButton();
        optioncRB = new javax.swing.JRadioButton();
        questionLBL = new javax.swing.JLabel();
        optiondRB = new javax.swing.JRadioButton();
        quizBTN = new javax.swing.JButton();
        nextBTN = new javax.swing.JButton();
        imageLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipsTA.setEditable(false);
        tipsTA.setColumns(20);
        tipsTA.setRows(5);
        jScrollPane1.setViewportView(tipsTA);

        WellnessEducationLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        WellnessEducationLBL.setText("Wellness Education");

        mainMenuBTN.setBackground(new java.awt.Color(120, 140, 180));
        mainMenuBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainMenuBTN.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBTN.setText("Main Menu");
        mainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBTNActionPerformed(evt);
            }
        });

        HabitBuilderBTN.setBackground(new java.awt.Color(120, 140, 180));
        HabitBuilderBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HabitBuilderBTN.setForeground(new java.awt.Color(255, 255, 255));
        HabitBuilderBTN.setText("Habit Builder");
        HabitBuilderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitBuilderBTNActionPerformed(evt);
            }
        });

        HealthTrackerBTN.setBackground(new java.awt.Color(120, 140, 180));
        HealthTrackerBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HealthTrackerBTN.setForeground(new java.awt.Color(255, 255, 255));
        HealthTrackerBTN.setText("Health Tracker");
        HealthTrackerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthTrackerBTNActionPerformed(evt);
            }
        });

        EXITbtn.setBackground(new java.awt.Color(120, 140, 180));
        EXITbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EXITbtn.setForeground(new java.awt.Color(255, 255, 255));
        EXITbtn.setText("Exit");
        EXITbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITbtnActionPerformed(evt);
            }
        });

        healthtipsLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        healthtipsLBL.setText("Health Tips");

        showtipBTN.setBackground(new java.awt.Color(120, 140, 180));
        showtipBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showtipBTN.setForeground(new java.awt.Color(255, 255, 255));
        showtipBTN.setText("Show Tip");
        showtipBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtipBTNActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionaRB);
        optionaRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        optionaRB.setText("Option A");
        optionaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionaRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionbRB);
        optionbRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        optionbRB.setText("Option B");
        optionbRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionbRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(optioncRB);
        optioncRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        optioncRB.setText("Option C");
        optioncRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optioncRBActionPerformed(evt);
            }
        });

        questionLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        questionLBL.setText("Click start quiz to generate a question");

        buttonGroup1.add(optiondRB);
        optiondRB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        optiondRB.setText("Option D");
        optiondRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optiondRBActionPerformed(evt);
            }
        });

        quizBTN.setBackground(new java.awt.Color(120, 140, 180));
        quizBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quizBTN.setForeground(new java.awt.Color(255, 255, 255));
        quizBTN.setText("Start Quiz");
        quizBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBTNActionPerformed(evt);
            }
        });

        nextBTN.setBackground(new java.awt.Color(120, 140, 180));
        nextBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextBTN.setForeground(new java.awt.Color(255, 255, 255));
        nextBTN.setText("Next");
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });

        imageLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Michael/Images/HealthyLifee.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(HealthTrackerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(HabitBuilderBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(showtipBTN)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optiondRB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(optioncRB, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mainMenuBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(EXITbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quizBTN)
                                .addGap(18, 18, 18)
                                .addComponent(nextBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(optionbRB, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(optionaRB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(questionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(healthtipsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(imageLBL)
                .addGap(33, 33, 33)
                .addComponent(WellnessEducationLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {optionaRB, optionbRB, optioncRB, optiondRB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(WellnessEducationLBL)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imageLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(healthtipsLBL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showtipBTN)
                        .addGap(30, 30, 30)
                        .addComponent(HabitBuilderBTN)
                        .addGap(31, 31, 31)
                        .addComponent(HealthTrackerBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quizBTN)
                            .addComponent(nextBTN))))
                .addGap(27, 27, 27)
                .addComponent(questionLBL)
                .addGap(18, 18, 18)
                .addComponent(optionaRB)
                .addGap(18, 18, 18)
                .addComponent(optionbRB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(mainMenuBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optioncRB)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optiondRB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXITbtn))
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {optionaRB, optionbRB, optioncRB, optiondRB});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HealthTrackerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthTrackerBTNActionPerformed
        // TODO add your handling code here:
         new HealthTracker().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_HealthTrackerBTNActionPerformed

    private void HabitBuilderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitBuilderBTNActionPerformed
        // TODO add your handling code here:
        new HabitBuilder().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_HabitBuilderBTNActionPerformed

    private void mainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBTNActionPerformed
        // TODO add your handling code here:
        new HealthGUI().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_mainMenuBTNActionPerformed

    private void EXITbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITbtnActionPerformed

    private void optionaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionaRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionaRBActionPerformed

    private void optionbRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionbRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionbRBActionPerformed

    private void optioncRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optioncRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optioncRBActionPerformed

    private void optiondRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optiondRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optiondRBActionPerformed

    private void showtipBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtipBTNActionPerformed
        // TODO add your handling code here:
        Random r = new Random();
        int index = r.nextInt(tipsList.size());
        tipsTA.setText(tipsList.get(index).getText());

    }//GEN-LAST:event_showtipBTNActionPerformed

    private void quizBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBTNActionPerformed
        // TODO add your handling code here:
        score = 0;              
        currentQuizIndex = 0;   
        quizStarted = true;     
        displayQuestion(currentQuizIndex);

    }//GEN-LAST:event_quizBTNActionPerformed

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        // TODO add your handling code here:
         if (!quizStarted) {
        javax.swing.JOptionPane.showMessageDialog(this, "Click Start Quiz before moving to the next question.");
        return;
    }

    // Check an answer is selected
    int selected = -1;
    if (optionaRB.isSelected()) {
        selected = 0;
    } else if (optionbRB.isSelected()) {
        selected = 1;
    } else if (optioncRB.isSelected()) {
        selected = 2;
    } else if (optiondRB.isSelected()) {
        selected = 3;
    }

    if (selected == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an answer before going to the next question.");
        return;
    }

    // Grade this question
    QuizQuestion q = quizList.get(currentQuizIndex);
    if (selected == q.getCorrectIndex()) {
        score++;
    }

    // If this was the last question, show result
    if (currentQuizIndex == quizList.size() - 1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Quiz finished!\nYour score: " + score + " out of " + quizList.size()
        );

        // Reset quiz state
        quizStarted = false;
        buttonGroup1.clearSelection();
        questionLBL.setText("Click start quiz to generate a question");
        optionaRB.setText("Option A");
        optionbRB.setText("Option B");
        optioncRB.setText("Option C");
        optiondRB.setText("Option D");
    } else {
        // Otherwise go to next question
        currentQuizIndex++;
        displayQuestion(currentQuizIndex);
       }
    
    }//GEN-LAST:event_nextBTNActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WellnessEducation().setVisible(true));
    }
   
    private void loadTips() {
    tipsList.clear();

    tipsList.add(new HealthTip("Drink 1–2 litres of water daily to stay hydrated."));
    tipsList.add(new HealthTip("Aim for 7–9 hours of sleep each night."));
    tipsList.add(new HealthTip("Take regular movement breaks during the day, especially if you sit a lot."));
    tipsList.add(new HealthTip("Try to eat a variety of colourful fruit and vegetables each day."));
    tipsList.add(new HealthTip("Limit sugary drinks and choose water most of the time."));
    tipsList.add(new HealthTip("Spend a few minutes each day focusing on your breathing to reduce stress."));
    tipsList.add(new HealthTip("Try to get outside for some daylight and fresh air every day."));
    tipsList.add(new HealthTip("Avoid using your phone or screens right before bed."));
    tipsList.add(new HealthTip("Set small, realistic goals for building new healthy habits."));
    tipsList.add(new HealthTip("Talk to friends, family or someone you trust if you feel stressed or overwhelmed."));
}


    private void loadQuestions() {
    quizList.clear(); // just in case

    quizList.add(new QuizQuestion(
        "Which habit improves sleep quality?",
        new String[]{
            "Keeping a consistent sleep schedule",
            "Drinking energy drinks late at night",
            "Using your phone in bed",
            "Going to bed at a different time every day"
        },
        0));

    quizList.add(new QuizQuestion(
        "What is a balanced snack?",
        new String[]{
            "Apple and a handful of nuts",
            "Crisps and cola",
            "Chocolate bar and coffee",
            "White bread and butter"
        },
        0));

    quizList.add(new QuizQuestion(
        "How much moderate exercise is recommended?",
        new String[]{
            "150 minutes per week",
            "10 minutes weekly",
            "Only when you feel like it",
            "3 hours per day"
        },
        0));

    quizList.add(new QuizQuestion(
        "Which drink is usually the healthiest everyday choice?",
        new String[]{
            "Water",
            "Energy drink",
            "Fizzy drink",
            "Sugary iced tea"
        },
        0));

    quizList.add(new QuizQuestion(
        "Which habit can help reduce daily stress?",
        new String[]{
            "Taking short breaks and breathing deeply",
            "Ignoring how you feel",
            "Working non-stop without breaks",
            "Eating lots of junk food"
        },
        0));

    quizList.add(new QuizQuestion(
        "Which breakfast is the best example of a healthy start?",
        new String[]{
            "Porridge with fruit",
            "Chocolate bar and a fizzy drink",
            "Nothing at all",
            "Crisps and coffee"
        },
        0));

    quizList.add(new QuizQuestion(
        "What is a good way to look after your mental wellbeing?",
        new String[]{
            "Talking to someone you trust about your feelings",
            "Keeping everything to yourself",
            "Avoiding all friends and family",
            "Only scrolling on social media"
        },
        0));

    quizList.add(new QuizQuestion(
        "Why is regular movement important during the day?",
        new String[]{
            "It improves circulation and reduces stiffness",
            "It makes you more tired and unfocused",
            "It stops you from sleeping at night",
            "It replaces the need for healthy food"
        },
        0));
}


    private void displayQuestion(int index) {
        QuizQuestion q = quizList.get(index);

        questionLBL.setText(q.getQuestion());
        optionaRB.setText(q.getOptions()[0]);
        optionbRB.setText(q.getOptions()[1]);
        optioncRB.setText(q.getOptions()[2]);
        optiondRB.setText(q.getOptions()[3]);

        buttonGroup1.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXITbtn;
    private javax.swing.JButton HabitBuilderBTN;
    private javax.swing.JButton HealthTrackerBTN;
    private javax.swing.JLabel WellnessEducationLBL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel healthtipsLBL;
    private javax.swing.JLabel imageLBL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBTN;
    private javax.swing.JButton nextBTN;
    private javax.swing.JRadioButton optionaRB;
    private javax.swing.JRadioButton optionbRB;
    private javax.swing.JRadioButton optioncRB;
    private javax.swing.JRadioButton optiondRB;
    private javax.swing.JLabel questionLBL;
    private javax.swing.JButton quizBTN;
    private javax.swing.JButton showtipBTN;
    private javax.swing.JTextArea tipsTA;
    // End of variables declaration//GEN-END:variables
}
